CREATE TABLE rental_fund_auth_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  auth_order_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  user_account_id BIGINT NOT NULL,
  alipay_user_id VARCHAR(128) NOT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  auth_type VARCHAR(32) NOT NULL,
  auth_status VARCHAR(32) NOT NULL,
  auth_amount DECIMAL(12, 2) NOT NULL,
  frozen_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  captured_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  released_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  out_request_no VARCHAR(64) NOT NULL,
  alipay_auth_no VARCHAR(128) NULL,
  alipay_operation_id VARCHAR(128) NULL,
  order_str TEXT NULL,
  subject VARCHAR(128) NOT NULL,
  last_error VARCHAR(255) NULL,
  authorized_at DATETIME NULL,
  closed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fund_auth_order_no (auth_order_no),
  UNIQUE KEY uk_fund_auth_out_request_no (out_request_no),
  KEY idx_fund_auth_order (order_id),
  KEY idx_fund_auth_user (user_account_id),
  KEY idx_fund_auth_status (auth_status),
  KEY idx_fund_auth_alipay_auth_no (alipay_auth_no)
);

CREATE TABLE rental_fund_auth_operation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  operation_no VARCHAR(64) NOT NULL,
  auth_order_id BIGINT NOT NULL,
  bill_id BIGINT NULL,
  payment_id BIGINT NULL,
  operation_type VARCHAR(32) NOT NULL,
  operation_status VARCHAR(32) NOT NULL,
  amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  out_request_no VARCHAR(64) NOT NULL,
  alipay_trade_no VARCHAR(128) NULL,
  alipay_operation_id VARCHAR(128) NULL,
  remark VARCHAR(255) NULL,
  failure_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fund_auth_operation_no (operation_no),
  UNIQUE KEY uk_fund_auth_operation_request_no (out_request_no),
  KEY idx_fund_auth_operation_auth (auth_order_id),
  KEY idx_fund_auth_operation_bill (bill_id),
  KEY idx_fund_auth_operation_status (operation_status)
);

CREATE TABLE rental_fund_auth_notify (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  auth_order_id BIGINT NULL,
  notify_id VARCHAR(128) NULL,
  out_order_no VARCHAR(64) NULL,
  out_request_no VARCHAR(64) NULL,
  auth_no VARCHAR(128) NULL,
  operation_id VARCHAR(128) NULL,
  auth_status VARCHAR(64) NULL,
  total_freeze_amount DECIMAL(12, 2) NULL,
  rest_amount DECIMAL(12, 2) NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  raw_payload TEXT NOT NULL,
  failure_reason VARCHAR(255) NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fund_auth_notify_id (notify_id),
  KEY idx_fund_auth_notify_order (auth_order_id),
  KEY idx_fund_auth_notify_out_order (out_order_no)
);
