CREATE TABLE user_identity_verification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_account_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  front_image_url TEXT NULL,
  back_image_url TEXT NULL,
  ocr_status VARCHAR(32) NOT NULL,
  real_name_status VARCHAR(32) NOT NULL,
  real_name_masked VARCHAR(64) NULL,
  id_no_masked VARCHAR(64) NULL,
  id_no_hash VARCHAR(128) NULL,
  gender VARCHAR(16) NULL,
  birth_date VARCHAR(32) NULL,
  address_masked VARCHAR(255) NULL,
  ocr_provider VARCHAR(64) NULL,
  certify_provider VARCHAR(64) NULL,
  external_certify_id VARCHAR(128) NULL,
  failure_reason VARCHAR(255) NULL,
  verified_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_identity_user (user_account_id),
  KEY idx_identity_order (order_id),
  KEY idx_identity_real_name_status (real_name_status)
);

CREATE TABLE contract_template (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  template_code VARCHAR(64) NOT NULL,
  template_name VARCHAR(128) NOT NULL,
  contract_type VARCHAR(32) NOT NULL,
  version_no VARCHAR(32) NOT NULL,
  provider_template_id VARCHAR(128) NULL,
  content TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_contract_template_code_version (template_code, version_no),
  KEY idx_contract_template_type_status (contract_type, status)
);

CREATE TABLE rental_contract (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  contract_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  user_account_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  template_id BIGINT NOT NULL,
  contract_type VARCHAR(32) NOT NULL,
  contract_status VARCHAR(32) NOT NULL,
  provider VARCHAR(64) NULL,
  external_flow_id VARCHAR(128) NULL,
  sign_url TEXT NULL,
  archive_pdf_url TEXT NULL,
  rendered_content TEXT NOT NULL,
  failure_reason VARCHAR(255) NULL,
  sent_at DATETIME NULL,
  signed_at DATETIME NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_rental_contract_no (contract_no),
  KEY idx_rental_contract_order (order_id),
  KEY idx_rental_contract_user (user_account_id),
  KEY idx_rental_contract_status (contract_status)
);

CREATE TABLE contract_notify (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  contract_id BIGINT NULL,
  external_flow_id VARCHAR(128) NULL,
  notify_id VARCHAR(128) NULL,
  contract_status VARCHAR(64) NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  raw_payload TEXT NOT NULL,
  failure_reason VARCHAR(255) NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_contract_notify_id (notify_id),
  KEY idx_contract_notify_contract (contract_id),
  KEY idx_contract_notify_flow (external_flow_id)
);
