CREATE TABLE voucher_verification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_platform VARCHAR(32) NOT NULL,
  voucher_code VARCHAR(128) NOT NULL,
  user_account_id BIGINT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  store_sku_id BIGINT NOT NULL,
  package_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  sign_fee_bill_id BIGINT NULL,
  verify_status VARCHAR(32) NOT NULL,
  voucher_title VARCHAR(128) NULL,
  voucher_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  sign_fee_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  external_prepare_id VARCHAR(128) NULL,
  external_verify_id VARCHAR(128) NULL,
  external_consume_id VARCHAR(128) NULL,
  valid_from DATETIME NULL,
  valid_to DATETIME NULL,
  retry_count INT NOT NULL DEFAULT 0,
  raw_payload TEXT NULL,
  failure_reason VARCHAR(255) NULL,
  verified_at DATETIME NULL,
  consumed_at DATETIME NULL,
  exception_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_voucher_platform_code (source_platform, voucher_code),
  KEY idx_voucher_user (user_account_id),
  KEY idx_voucher_order (order_id),
  KEY idx_voucher_store_status (store_id, verify_status),
  KEY idx_voucher_status (verify_status)
);
