CREATE TABLE settlement_statement (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  statement_no VARCHAR(64) NOT NULL,
  statement_month VARCHAR(7) NOT NULL,
  beneficiary_type VARCHAR(32) NOT NULL,
  beneficiary_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL DEFAULT 0,
  store_id BIGINT NOT NULL DEFAULT 0,
  rent_base_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  sign_fee_income_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  rent_share_income_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  operation_fee_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  maintenance_deduct_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  adjustment_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  payable_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  order_count INT NOT NULL DEFAULT 0,
  bill_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at DATETIME NULL,
  paid_at DATETIME NULL,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_settlement_statement_scope (statement_month, beneficiary_type, beneficiary_id, merchant_id, store_id),
  UNIQUE KEY uk_settlement_statement_no (statement_no),
  KEY idx_settlement_statement_month (statement_month),
  KEY idx_settlement_statement_status (status),
  KEY idx_settlement_statement_beneficiary (beneficiary_type, beneficiary_id),
  KEY idx_settlement_statement_store (merchant_id, store_id)
);

CREATE TABLE settlement_statement_line (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  statement_id BIGINT NOT NULL,
  line_no VARCHAR(64) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  bill_id BIGINT NULL,
  asset_id BIGINT NULL,
  merchant_id BIGINT NOT NULL DEFAULT 0,
  store_id BIGINT NOT NULL DEFAULT 0,
  investor_id BIGINT NOT NULL DEFAULT 0,
  line_type VARCHAR(64) NOT NULL,
  amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  occurred_at DATETIME NULL,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_settlement_statement_line_no (line_no),
  KEY idx_settlement_statement_line_statement (statement_id),
  KEY idx_settlement_statement_line_source (source_type, source_id),
  KEY idx_settlement_statement_line_order (order_id),
  KEY idx_settlement_statement_line_bill (bill_id),
  KEY idx_settlement_statement_line_store (merchant_id, store_id),
  KEY idx_settlement_statement_line_investor (investor_id)
);
