CREATE TABLE external_rental_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  record_no VARCHAR(64) NOT NULL,
  source_platform VARCHAR(32) NOT NULL,
  external_order_no VARCHAR(128) NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  store_sku_id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  package_id BIGINT NOT NULL,
  customer_name VARCHAR(64) NOT NULL,
  customer_phone VARCHAR(32) NOT NULL,
  frame_asset_id BIGINT NULL,
  battery_asset_id BIGINT NULL,
  order_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  external_rental_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  sign_fee_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  deposit_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  lease_unit VARCHAR(24) NOT NULL,
  lease_value INT NOT NULL,
  total_periods INT NOT NULL DEFAULT 1,
  rent_started_at DATETIME NOT NULL,
  expected_return_at DATETIME NULL,
  finished_at DATETIME NULL,
  return_store_id BIGINT NULL,
  termination_reason VARCHAR(255) NULL,
  remark VARCHAR(255) NULL,
  created_by_account_id BIGINT NULL,
  updated_by_account_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_external_rental_order_record_no (record_no),
  KEY idx_external_rental_order_status (order_status),
  KEY idx_external_rental_order_store (store_id),
  KEY idx_external_rental_order_merchant (merchant_id),
  KEY idx_external_rental_order_source (source_platform),
  KEY idx_external_rental_order_start (rent_started_at),
  KEY idx_external_rental_order_frame_asset (frame_asset_id),
  KEY idx_external_rental_order_battery_asset (battery_asset_id)
);

CREATE TABLE external_rental_order_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_order_id BIGINT NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NOT NULL,
  operation_type VARCHAR(32) NOT NULL,
  operator_account_id BIGINT NULL,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_external_rental_order_log_order (external_order_id),
  KEY idx_external_rental_order_log_created (created_at)
);
