CREATE TABLE rental_payment_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  payment_no VARCHAR(64) NOT NULL,
  bill_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  user_account_id BIGINT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  pay_channel VARCHAR(32) NOT NULL,
  pay_status VARCHAR(32) NOT NULL,
  pay_amount DECIMAL(12, 2) NOT NULL,
  paid_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  subject VARCHAR(128) NOT NULL,
  payer_alipay_user_id VARCHAR(128) NULL,
  alipay_trade_no VARCHAR(128) NULL,
  refund_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  paid_at DATETIME NULL,
  closed_at DATETIME NULL,
  last_error VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_payment_no (payment_no),
  KEY idx_payment_bill (bill_id),
  KEY idx_payment_order (order_id),
  KEY idx_payment_status (pay_status),
  KEY idx_payment_alipay_trade_no (alipay_trade_no)
);

CREATE TABLE rental_payment_callback (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  payment_id BIGINT NULL,
  notify_id VARCHAR(128) NULL,
  out_trade_no VARCHAR(64) NULL,
  alipay_trade_no VARCHAR(128) NULL,
  trade_status VARCHAR(64) NULL,
  total_amount DECIMAL(12, 2) NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  raw_payload TEXT NOT NULL,
  failure_reason VARCHAR(255) NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_payment_callback_notify_id (notify_id),
  KEY idx_payment_callback_payment (payment_id),
  KEY idx_payment_callback_out_trade_no (out_trade_no)
);
