CREATE TABLE rental_pay_agreement (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  agreement_no VARCHAR(128) NULL,
  external_agreement_no VARCHAR(64) NOT NULL,
  user_account_id BIGINT NOT NULL,
  alipay_user_id VARCHAR(128) NOT NULL,
  order_id BIGINT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  agreement_type VARCHAR(32) NOT NULL,
  agreement_status VARCHAR(32) NOT NULL,
  personal_product_code VARCHAR(64) NOT NULL,
  sign_scene VARCHAR(64) NOT NULL,
  max_single_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  sign_url TEXT NULL,
  sign_time DATETIME NULL,
  valid_time DATETIME NULL,
  invalid_time DATETIME NULL,
  last_error VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_pay_agreement_external_no (external_agreement_no),
  UNIQUE KEY uk_pay_agreement_no (agreement_no),
  KEY idx_pay_agreement_user (user_account_id),
  KEY idx_pay_agreement_order (order_id),
  KEY idx_pay_agreement_status (agreement_status)
);

CREATE TABLE rental_agreement_notify (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  agreement_id BIGINT NULL,
  notify_id VARCHAR(128) NULL,
  external_agreement_no VARCHAR(64) NULL,
  agreement_no VARCHAR(128) NULL,
  agreement_status VARCHAR(32) NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  raw_payload TEXT NOT NULL,
  failure_reason VARCHAR(255) NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_agreement_notify_id (notify_id),
  KEY idx_agreement_notify_agreement (agreement_id),
  KEY idx_agreement_notify_external_no (external_agreement_no)
);

CREATE TABLE rental_deduct_batch (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  batch_no VARCHAR(64) NOT NULL,
  batch_status VARCHAR(32) NOT NULL,
  planned_count INT NOT NULL DEFAULT 0,
  success_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  remark VARCHAR(255) NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_deduct_batch_no (batch_no),
  KEY idx_deduct_batch_status (batch_status)
);

CREATE TABLE rental_deduct_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  deduct_no VARCHAR(64) NOT NULL,
  batch_no VARCHAR(64) NULL,
  bill_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  agreement_id BIGINT NOT NULL,
  agreement_no VARCHAR(128) NOT NULL,
  payment_id BIGINT NULL,
  deduct_status VARCHAR(32) NOT NULL,
  deduct_amount DECIMAL(12, 2) NOT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  alipay_trade_no VARCHAR(128) NULL,
  last_error VARCHAR(255) NULL,
  requested_at DATETIME NULL,
  success_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_deduct_no (deduct_no),
  UNIQUE KEY uk_deduct_bill_active (bill_id, deduct_status),
  KEY idx_deduct_batch_no (batch_no),
  KEY idx_deduct_bill (bill_id),
  KEY idx_deduct_order (order_id),
  KEY idx_deduct_status_retry (deduct_status, next_retry_at)
);
