package com.xniu.rental.settlement.model;

public enum SettlementStatementLineType {
    MERCHANT_SIGN_FEE,
    MERCHANT_RENT_SHARE,
    MERCHANT_MAINTENANCE_REIMBURSE,
    MERCHANT_MAINTENANCE_DEDUCT,
    MERCHANT_ADJUSTMENT,
    INVESTOR_GROSS_RENT,
    INVESTOR_OPERATION_FEE,
    INVESTOR_MAINTENANCE_DEDUCT,
    INVESTOR_ADJUSTMENT
}
